name: Deploy CloudFleet to AWS

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::928003954894:role/CloudFleetGitHubDeployRole
          aws-region: ap-south-1

      - name: Create deployment ZIP
        run: |
          zip -r cloudfleet.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x "*.zip"

      - name: Upload deployment bundle to S3
        run: |
          aws s3 cp cloudfleet.zip \
            s3://cloudfleet-deployments-928003954894/cloudfleet-${{ github.sha }}.zip

      - name: Create Elastic Beanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name CloudFleet \
            --version-label github-${{ github.sha }} \
            --source-bundle S3Bucket=cloudfleet-deployments-928003954894,S3Key=cloudfleet-${{ github.sha }}.zip

      - name: Deploy to CloudFleet-dev
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name CloudFleet-dev \
            --version-label github-${{ github.sha }}